export const CREATE_USER = "CREATE_USER"

export const SET_COLLECTIONS = "SET_COLLECTIONS"
export const SET_IMAGE_TO_COLLECT = "SET_IMAGE_TO_COLLECT"
export const ADD_INTO_COLLECTION = "ADD_INTO_COLLECTION"
export const SET_IMAGE_TO_VIEW ="SET_IMAGE_TO_VIEW"
export const TOGGLE_MODAL = "TOGGLE_MODAL"

export const SET_PHOTOS = "SET_PHOTOS"
export const VIEW_POST = "VIEW_POST"
export const UPDATE_POST = "UPDATE_PHOTO"
export const REMOVE_POST = "REMOVE_POST"
export const TOGGLE_SPINNER = "TOGGLE_SPINNER"

